apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx
spec:
  type: NodePort # exposes the Service on <nodeIP>:30080
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80        # port exposed by the Service (cluster-internal)
      targetPort: http # named port on the Pod
      nodePort: 30380  # fixed port on every node (range: 30000-32767)
